language: node_js
cache:
  timeout: 600
  directories:
    - node_modules
    - apps/marketplace-controller/node_modules
    - apps/bancor-formula/node_modules
    - apps/bancor-market-maker/node_modules
    - apps/presale/node_modules
    - shared/interfaces/node_modules
    - shared/test-helpers/node_modules
notifications:
  email: false
node_js:
  - '10'
install:
  - travis_wait 60 npm install
jobs:
  include:
    - stage: linting
      script: npm run lint
      name: 'All'
    - stage: tests
      script: npm run test:controller
      name: 'Marketplace Controller'
    - script: npm run test:bancor-market-maker
      name: 'Bancor Market Maker'
    - script: npm run test:presale
      name: 'Presale'
    - stage: coverage
      script: npm run coverage:controller
      name: 'Marketplace Controller'
    - script: npm run coverage:bancor-market-maker
      name: 'Bancor Market Maker'
    - script: npm run coverage:presale
      name: 'Presale'
after_success:
  - ./node_modules/.bin/lcov-result-merger 'apps/*/coverage/lcov.info' | ./node_modules/.bin/coveralls
